### ISSUE TITLE
SUPREME AUTOFILL PROBLEM

### ISSUE THREAD

**Issue by classichahn** [alexsnkr/sss-autofill#4]
IT WONT AUTOMATICALLY FILL THE STATE INFORMATION ON SUPREME CHECKOUT PAGE. OTHER THINGS SEEM GOOD

**Comment by carlzoo** [comment]
https://github.com/alexsnkr/sss-autofill/blob/master/src/inject/supreme.js#L14

The developer has currently commented out the code for autofilling states. 

I created a quick fix here: https://github.com/alexsnkr/sss-autofill/pull/8

**Comment by alexsnkr** [comment]
This has been fixed in the latest version.
Download it from the chrome store to receive updates.
https://chrome.google.com/webstore/detail/sss-autofill/gdhmefadngapdfphedlcimcdplachcip

The version with this fixed is currently being reviewed by google, so it will take a few days to get the update.
