### ISSUE TITLE
Error in Setup 

### ISSUE THREAD

**Issue by reactiver001** [alexsnkr/sss-autofill#7]
I try install version 0.0.4 but have this error

Downloads/sss-autofill-0.0.4.zip. Could not unzip extension for install.
Thanks and good job

**Comment by carlzoo** [comment]
You can install by unzipping. Click the load extension button and select your unzipped folder.

**Comment by reactiver001** [comment]
Tried that way and still giving the same error ..

**Comment by alexsnkr** [comment]
It's on the chrome store now, install it from there 
https://chrome.google.com/webstore/detail/sss-autofill/gdhmefadngapdfphedlcimcdplachcip
