### ISSUE TITLE
Add Provinces for Canada in the states field

### ISSUE THREAD

**Issue by carlzoo** [alexsnkr/sss-autofill#9]
Supreme supports shipping to Canada so this should be an expected featured.

**Comment by alexsnkr** [comment]
You can manually enter your country and state in the latest version.

Download it from the chrome store to receive updates -https://chrome.google.com/webstore/detail/sss-autofill/gdhmefadngapdfphedlcimcdplachcip

The version with this fix is currently being reviewed by google, so it will take a few days to get the update.
